[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_OPTIONS = "--openssl-legacy-provider"
  CI = "false"

[context.production.environment]
  REACT_APP_API_URL = "https://nexusshop-bhxb.onrender.com"
  REACT_APP_ENV = "production"
  REACT_APP_SITE_URL = "https://your-site.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200